name: Selenium Test Automation CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # ✅ Step 3: Install Chrome (needed for Selenium tests)
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 4: Run Build + Tests
      - name: Build & Run Tests
        run: mvn clean test

      # Step 5: Generate Allure Report
      - name: Generate Allure Report
        run: mvn allure:report
        continue-on-error: true

      # Step 6: Upload Allure report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      # Step 7: Send Email Notification (optional)
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Test Automation Report"
          to: "nansuman2@gmail.com"
          from: ${{ secrets.EMAIL_USER }}
          body: "Tests completed. Please check the attached Allure report."
          attachments: target/site/allure-maven-plugin/*

      # Step 8: Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: success() || failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          publish_branch: gh-pages
